---
- name: Install Patroni and dependencies
  pip:
    name:
      - psycopg2
      - cryptography
      - "patroni[etcd,raft]"
    state: present

- name: Install etcd
  apt:
    name:
      - etcd
    state: present
