---
- name: Install pgBackRest
  apt:
    pkg:
      - pgbackrest
    state: present

- name: Create pgBackRest data directory
  file:
    path: "{{ pgbackrest_directory }}"
    owner: "{{ timescaledb_linux_user }}"
    mode: "0750"
    state: directory

- name: Create pgBackRest configuration directory
  file:
    path: "/etc/pgbackrest"
    state: directory

- name: Configure pgBackRest
  template:
    src: "../files/pgbackrest.conf.tmpl"
    dest: "/etc/pgbackrest/pgbackrest.conf"
