---
- name: Promtail | Install rsyslog
  include_role:
    name: robertdebock.rsyslog
    vars:
      rsyslog_config_file_format: advanced

# The role has support for a remote receiver, but it doesn’t quite
# match what Promtail needs.
- name: rsyslog | Add forwarding rule
  copy:
    # Queuing based on <https://utcc.utoronto.ca/~cks/space/blog/sysadmin/PromtailRsyslogForwarderSetup>.
    content: 'action(type="omfwd" target="127.0.0.1" protocol="tcp" port="1514" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted" KeepAlive="on" action.resumeRetryCount="-1" queue.type="linkedlist" queue.size="50000")'
    dest: "/etc/rsyslog.d/promtail.conf"
    mode: "0644"
    owner: "root"
    group: "root"
    validate: "rsyslogd -N1 -f %s"

- name: Promtail | Install support packages
  apt:
    pkg:
      - unzip
    state: present

- name: Promtail | Download
  get_url:
    url: "{{ promtail_url }}"
    dest: "/tmp/promtail.zip"

- name: Promtail | Add user
  user:
    name: "{{ promtail_username }}"
    append: yes
    groups:
      - adm
    state: present

- name: Promtail | Extract
  unarchive:
    src: "/tmp/promtail.zip"
    dest: "/usr/local/bin"
    mode: "u=rwx,g=rx,o=rx"
    owner: "{{ promtail_username }}"

- name: Promtail | Create directory
  file:
    path: /opt/promtail
    owner: "{{ promtail_username }}"
    group: "{{ promtail_username }}"
    mode: "u=rwx,go=rx"
    state: directory

- name: Promtail | Copy configuration
  copy:
    src: "promtail.conf.yaml"
    dest: "/opt/promtail/promtail.yaml"
    mode: "u=rw,go=r"
    owner: "{{ promtail_username }}"
    group: "{{ promtail_username }}"

- name: Promtail | Create service
  template:
    src: "promtail.service.j2"
    dest: "/etc/systemd/system/promtail.service"
    mode: "u=rw,go=r"

- name: Promtail | Start service
  systemd:
    daemon_reload: yes
    name: promtail
    enabled: yes
    state: "started"
