---
- name: Add PostgreSQL key
  apt_key:
    id: "B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8"
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: Add PostgreSQL repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
  register: postgresql_repo

- name: Add TimescaleDB PPA key
  apt_key:
    id: "1005FB68604CE9B8F6879CF759F18EDF47F24417"
    url: "https://packagecloud.io/timescale/timescaledb/gpgkey"
    state: present

- name: Add TimescaleDB to sources list
  apt_repository:
    repo: "deb https://packagecloud.io/timescale/timescaledb/debian/ {{ ansible_distribution_release }} main"
    state: present
  register: timescaledb_repo

- name: Install postgresql-common
  apt:
    pkg:
      - postgresql-common
    update_cache: yes

- name: Disable creating new cluster
  lineinfile:
    path: "/etc/postgresql-common/createcluster.conf"
    line: "create_main_cluster = false"
    regexp: "^#?create_main_cluster"
    state: present

- name: Install TimescaleDB and PostgreSQL dev tools
  apt:
    pkg:
      - "{{ timescaledb_package }}"
      - timescaledb-tools
      - "{{ postgresql_dev_package }}"
      - gnupg
      - postgresql-14
      - apt-transport-https
      - wget
    state: present
