---
- name: Add PostgreSQL key
  apt_key:
    id: "B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8"
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: Add PostgreSQL repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
  register: postgresql_repo

- name: Add TimescaleDB PPA key
  apt_key:
    id: "1005FB68604CE9B8F6879CF759F18EDF47F24417"
    url: "https://packagecloud.io/timescale/timescaledb/gpgkey"
    state: present

- name: Add TimescaleDB to sources list
  apt_repository:
    repo: "deb https://packagecloud.io/timescale/timescaledb/debian/ {{ ansible_distribution_release }} main"
    state: present
  register: timescaledb_repo

- name: Install TimescaleDB and PostgreSQL dev tools
  apt:
    pkg:
      - "{{ timescaledb_package }}"
      - timescaledb-tools
      - "{{ postgresql_dev_package }}"
      - gnupg
      - postgresql-common
      - postgresql-14
      - apt-transport-https
      - wget
    update_cache: yes
    state: present

- name: Set PostgreSQL to trust everything
  copy:
    dest: "{{ postgresql_directory }}/pg_hba.conf"
    content: >-
      host all all 0.0.0.0/0 trust
      local all all trust
    owner: "{{ timescaledb_linux_user }}"
    mode: "0600"
  register: postgresql_trust

- name: Set PostgreSQL to listen for connections on all addresses
  lineinfile:
    path: "{{ postgresql_directory }}/postgresql.conf"
    line: "listen_addresses = '*'"

- name: Compute MD5 of PostgreSQL configuration
  stat: path={{ postgresql_directory }}/postgresql.conf get_md5=yes
  register: existing_postgresql

- name: Tune TimescaleDB
  shell: "timescaledb-tune --yes"

- name: Compute new MD5 of PostgreSQL configuration
  stat: path={{ postgresql_directory }}/postgresql.conf get_md5=yes
  register: new_postgresql

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
  when: "existing_postgresql.stat.md5 != new_postgresql.stat.md5 or postgresql.trust_changed"
