---
- name: Install TimescaleDB
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/timescaledb.yml

- name: Install Promscale
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/promscale.yml

- name: Set up pgBackRest
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/pgbackrest.yml

- name: Install Patroni
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/patroni.yml
