---
- name: Configure journald
  hosts: all
  become: yes
  tasks:
    - name: "Minimize logging"
      ansible.builtin.lineinfile:
        dest: "/etc/systemd/journald.conf"
        regexp: "^.*{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      loop:
        - key: Storage
          value: volatile
        - key: MaxRetentionSec
          value: "8h"

- name: Install TimescaleDB
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/timescaledb.yml

- name: Install Promscale
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/promscale.yml

- name: Set up pgBackRest
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/pgbackrest.yml
      when: enable_pgbackrest | bool

- name: Install S3 tools
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/s3_tools.yml
      when: enable_s3_tools | bool

- name: Set up node_exporter
  hosts: all
  become: yes
  pre_tasks:
    - name: node_exporter | Create certificates directory
      file:
        path: /etc/node_exporter
        state: directory
    - name: node_exporter | Create empty TLS certificate files
      file:
        path: "/etc/node_exporter/{{ item }}"
        state: touch
      loop:
        - tls.crt
        - tls.key
  post_tasks:
    # Required to write files for textfile collector.
    - name: node_exporter | Add postgres user to node-exp group
      user:
        name: postgres
        groups:
          - node-exp
        append: yes
        state: present
  roles:
    - cloudalchemy.node_exporter
  vars:
    node_exporter_tls_server_config:
      cert_file: /etc/node_exporter/tls.crt
      key_file: /etc/node_exporter/tls.key
      client_ca_file: /etc/node_exporter/client_ca.crt
      client_auth_type: RequireAndVerifyClientCert

- name: Install postgres_exporter
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/postgres_exporter.yml

- name: Install rsyslog
  hosts: all
  become: yes
  # The role has support for a remote receiver, but it doesn’t quite
  # match what Promtail needs.
  post_tasks:
    - name: rsyslog | Add forwarding rule
      copy:
        # Queuing based on <https://utcc.utoronto.ca/~cks/space/blog/sysadmin/PromtailRsyslogForwarderSetup>.
        content: 'action(type="omfwd" target="127.0.0.1" protocol="tcp" port="1514" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted" KeepAlive="on" action.resumeRetryCount="-1" queue.type="linkedlist" queue.size="50000")'
        dest: "/etc/rsyslog.d/promtail.conf"
        mode: "0644"
        owner: "root"
        group: "root"
        validate: "rsyslogd -N1 -f %s"
  roles:
    - robertdebock.rsyslog
  vars:
    rsyslog_config_file_format: advanced

- name: Install Promtail
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/promtail.yml
