---
- name: Install TimescaleDB
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/timescaledb.yml

- name: Install Promscale
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/promscale.yml
