---
- name: Install TimescaleDB
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/timescaledb.yml

- name: Install Promscale
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/promscale.yml

- name: Set up pgBackRest
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/pgbackrest.yml

- name: Set up node_exporter
  hosts: all
  become: yes
  pre_tasks:
    - name: Create node_exporter cert dir
      file:
        path: "/etc/node_exporter"
        state: directory
        owner: root
        group: root

    - name: Create node_exporter private key
      openssl_privatekey:
        path: /etc/node_exporter/tls.key

    - name: Create node_exporter CSR
      openssl_csr:
        path: /etc/node_exporter/tls.csr
        privatekey_path: /etc/node_exporter/tls.key
        common_name: "localhost"

    - name: Create cert and key
      openssl_certificate:
        path: /etc/node_exporter/tls.cert
        csr_path: /etc/node_exporter/tls.csr
        privatekey_path: /etc/node_exporter/tls.key
        provider: selfsigned
  post_tasks:
    - name: Change ownership of directory
      file:
        dest: "/etc/node_exporter"
        owner: node-exp
        recurse: yes
        state: directory
  roles:
    - cloudalchemy.node_exporter
  vars:
    node_exporter_tls_server_config:
      cert_file: /etc/node_exporter/tls.cert
      key_file: /etc/node_exporter/tls.key
    # node_exporter_basic_auth_users:
    #   randomuser: examplepassword

- name: Install postgres_exporter
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/postgres_exporter.yml

- name: Install rsyslog
  hosts: all
  become: yes
  # The role has support for a remote receiver, but it doesn’t quite
  # match what Promtail needs.
  post_tasks:
    - name: rsyslog | Add forwarding rule
      copy:
        content: 'action(type="omfwd" protocol="tcp" port="3100" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted")'
        dest: "/etc/rsyslog.d/promtail.conf"
        mode: "0644"
        owner: "root"
        group: "root"
        validate: "rsyslogd -N1 -f %s"
  roles:
    - robertdebock.rsyslog
  vars:
    rsyslog_config_file_format: advanced

- name: Install Promtail
  hosts: all
  become: yes
  tasks:
    - include_tasks: ./tasks/promtail.yml
