name: Build and publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  publish:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: 1.8.3
          github-token: "${{ secrets.packer_token }}"
      - name: Initialize
        run: packer init server.pkr.hcl
        env:
          PACKER_GITHUB_API_TOKEN: "${{ secrets.packer_token }}"
      - name: Build and publish
        run: |
          packer build -only='*.ci' -var switch_name=ignore server.pkr.hcl
        env:
          PKR_VAR_do_image_name: "packer-timescaledb-server"
          PKR_VAR_root_password: "${{ secrets.publish_image_root_password }}"
          PKR_VAR_username: "timescaledb"
          PKR_VAR_password: "${{ secrets.publish_image_password }}"
          PKR_VAR_do_token: "${{ secrets.publish_do_token }}"
          PKR_VAR_do_region: "${{ secrets.publish_do_region }}"
          PKR_VAR_do_spaces_key: "${{ secrets.publish_do_spaces_key }}"
          PKR_VAR_do_spaces_secret_key: "${{ secrets.publish_do_spaces_secret_key }}"
          PKR_VAR_do_spaces_bucket: "${{ secrets.publish_do_spaces_bucket }}"
          PACKER_LOG: "1"
