name: Test build

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - README.md

env:
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: 1.8.3
      - name: Initialize
        run: packer init server.pkr.hcl
      - name: Validate
        run: packer validate -var-file .github.d/validation-variables.pkr.hcl server.pkr.hcl
      - name: Test build
        run: |
          packer build -except='digitalocean-import' -var-file .github.d/validation-variables.pkr.hcl server.pkr.hcl
        env:
          PACKER_LOG: "1"
